#-------------------------------
# 网站常见设置
title: AML.Blog
logo: AML-logo.svg  # 添加 logo
description: 


#-------------------------------
# 博主信息
author:
  name: 升卿
  image: https://s1.ax1x.com/2022/05/09/O8LgCd.jpg
  say-hello: 你好，我是 <strong>升卿</strong>。
  bio: 

#-------------------------------
# 联系链接
github: https://github.com/Hub-ShengQing
gitee: https://gitee.com/sheng-qing-s7
zhihu: https://www.zhihu.com/people/hewes
csdn: https://blog.csdn.net/Hewes


#-------------------------------
# 畅言评论
changyan-appid: cyw3W6zFu
changyan-conf: prod_b2bbba6538754464944d6c2f02347656

#-------------------------------
# 百度统计
baidu-analytics: true # 开启百度统计


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
